const employees = [
  { id: 1,
    garage_id: 1,
    valet_company_id: 1,
    user_id: 2,
  },
  { id: 2,
    garage_id: 1,
    valet_company_id: 1,
    user_id: 4,
  },
  { id: 3,
    garage_id: 1,
    valet_company_id: 1,
    user_id: 6,
  },
  { id: 4,
    garage_id: 1,
    valet_company_id: 1,
    user_id: 8,
  },
  { id: 5,
    garage_id: 2,
    valet_company_id: 2,
    user_id: 10,
  },
  { id: 6,
    garage_id: 3,
    valet_company_id: 2,
    user_id: 12,
  },
  { id: 7,
    garage_id: 4,
    valet_company_id: 2,
    user_id: 14,
  },
];

module.exports = employees;