employees = [
  { id: 1,
    garage_id: 1,
    valet_company_id: 1,
    name: 'Beck',
  },
  { id: 2,
    garage_id: 1,
    valet_company_id: 1,
    name: 'Jon',
  },
  { id: 3,
    garage_id: 2,
    valet_company_id: 1,
    name: 'Daniel',
  },
  { id: 4,
    garage_id: 2,
    valet_company_id: 1,
    name: 'Amelia',
  },
  { id: 5,
    garage_id: 1,
    valet_company_id: 2,
    name: 'Ledarius',
  },
  { id: 6,
    garage_id: 1,
    valet_company_id: 2,
    name: 'Michael',
  },
  { id: 7,
    garage_id: 1,
    valet_company_id: 2,
    name: 'Kurt',
  },
];

module.exports = employees;