parking_spots = [
  { id: 1,
    garage_id: 1,
    position: 1,
    available: 'reserved',
  },
  { id: 2,
    garage_id: 1,
    position: 2,
    available: 'available',
  },
  { id: 3,
    garage_id: 1,
    position: 3,
    available: 'occupied',
  },
  { id: 4,
    garage_id: 1,
    position: 4,
    available: 'available',
  },
  { id: 5,
    garage_id: 1,
    position: 5,
    available: 'available',
  },
  { id: 6,
    garage_id: 1,
    position: 6,
    available: 'available',
  },
  { id: 7,
    garage_id: 2,
    position: 1,
    available: 'reserved',
  },
  { id: 8,
    garage_id: 2,
    position: 2,
    available: 'reserved',
  },
  { id: 9,
    garage_id: 2,
    position: 3,
    available: 'occupied',
  },
  { id: 10,
    garage_id: 2,
    position: 4,
    available: 'occupied',
  },
  { id: 11,
    garage_id: 2,
    position: 5,
    available: 'available',
  },
  { id: 12,
    garage_id: 2,
    position: 6,
    available: 'available',
  },
];

module.exports = parking_spots;