users = [
  {
    id: 1,
    first_name: "Michael",
    last_name: "Cuellar",
    password: "password",
    email: "michaelcuellar@email.com",
    phone: "1234567890",
    is_employee: false,
    device_token: null,
  },
  {
    id: 2,
    first_name: "Michael",
    last_name: "Cuellar",
    password: "password",
    email: "michaelcuellar@workemail.com",
    phone: "1234567890",
    is_employee: true,
    device_token: 'test2',
  },
  {
    id: 3,
    first_name: "Daniel",
    last_name: "Park",
    password: "password",
    email: "danielpark@email.com",
    phone: "1234567890",
    is_employee: false,
    device_token: null,
  },
  {
    id: 4,
    first_name: "Daniel",
    last_name: "Park",
    password: "password",
    email: "danielpark@workemail.com",
    phone: "1234567890",
    is_employee: true,
    device_token: 'test4',
  },
  {
    id: 5,
    first_name: "Amelia",
    last_name: "Li",
    password: "password",
    email: "ameliali@email.com",
    phone: "1234567890",
    is_employee: false,
    device_token: null,
  },
  {
    id: 6,
    first_name: "Amelia",
    last_name: "Li",
    password: "password",
    email: "ameliali@workemail.com",
    phone: "1234567890",
    is_employee: true,
    device_token: 'test6',
  },
  {
    id: 7,
    first_name: "Beck",
    last_name: "Baimouradov",
    password: "password",
    email: "beckbaimouradov@email.com",
    phone: "1234567890",
    is_employee: false,
    device_token: null,
  },
  {
    id: 8,
    first_name: "Beck",
    last_name: "Baimouradov",
    password: "password",
    email: "beckbaimouradov@workemail.com",
    phone: "1234567890",
    is_employee: true,
    device_token: 'test8',
  },
  {
    id: 9,
    first_name: "Lederius",
    last_name: "Franklin",
    password: "password",
    email: "lederiusfranklin@email.com",
    phone: "1234567890",
    is_employee: false,
    device_token: null,
  },
  {
    id: 10,
    first_name: "Lederius",
    last_name: "Franklin",
    password: "password",
    email: "lederiusfranklin@workemail.com",
    phone: "1234567890",
    is_employee: true,
    device_token: 'test10',
  },
  {
    id: 11,
    first_name: "Jon",
    last_name: "Williams",
    password: "password",
    email: "jonwilliams@email.com",
    phone: "1234567890",
    is_employee: false,
    device_token: null,
  },
  {
    id: 12,
    first_name: "Jon",
    last_name: "Williams",
    password: "password",
    email: "jonwilliams@workemail.com",
    phone: "1234567890",
    is_employee: true,
    device_token: 'test12',
  },
  {
    id: 13,
    first_name: "Kurt",
    last_name: "Vardeman",
    password: "password",
    email: "kurtvardeman@email.com",
    phone: "1234567890",
    is_employee: false,
    device_token: null,
  },
  {
    id: 14,
    first_name: "Kurt",
    last_name: "Vardeman",
    password: "password",
    email: "kurtvardeman@workemail.com",
    phone: "1234567890",
    is_employee: true,
    device_token: 'test14',
  },
];

module.exports = users;
