const users = [
  { id: 1,
    first_name: 'Michael',
    last_name: 'Cuellar',
    email: 'michaelcuellar@email.com',
    password: 'password',
    phone: '1234567890',
    is_employee: false,
  },
  { id: 2,
    first_name: 'Michael',
    last_name: 'Cuellar',
    email: 'michaelcuellar@workemail.com',
    password: 'password',
    phone: '1234567890',
    is_employee: true,
  },
  { id: 3,
    first_name: 'Daniel',
    last_name: 'Park',
    email: 'danielpark@email.com',
    password: 'password',
    phone: '1234567890',
    is_employee: false,
  },
  { id: 4,
    first_name: 'Daniel',
    last_name: 'Park',
    email: 'danielpark@workemail.com',
    password: 'password',
    phone: '1234567890',
    is_employee: true,
  },
  { id: 5,
    first_name: 'Amelia',
    last_name: 'Li',
    email: 'ameiliali@email.com',
    password: 'password',
    phone: '1234567890',
    is_employee: false,
  },
  { id: 6,
    first_name: 'Ameilia',
    last_name: 'Li',
    email: 'ameiliali@workemail.com',
    password: 'password',
    phone: '1234567890',
    is_employee: true,
  },
  { id: 7,
    first_name: 'Beck',
    last_name: 'Baimouradov',
    email: 'beckbaimouradov@email.com',
    password: 'password',
    phone: '1234567890',
    is_employee: false,
  },
  { id: 8,
    first_name: 'Beck',
    last_name: 'Baimouradov',
    email: 'beckbaimouradov@workemail.com',
    password: 'password',
    phone: '1234567890',
    is_employee: true,
  },
  { id: 9,
    first_name: 'Lederius',
    last_name: 'Franklin',
    email: 'lederiusfranklin@email.com',
    password: 'password',
    phone: '1234567890',
    is_employee: false,
  },
  { id: 10,
    first_name: 'Lederius',
    last_name: 'Franklin',
    email: 'lederiusfranklin@workemail.com',
    password: 'password',
    phone: '1234567890',
    is_employee: true,
  },
  { id: 11,
    first_name: 'Jon',
    last_name: 'Williams',
    email: 'jonwilliams@email.com',
    password: 'password',
    phone: '1234567890',
    is_employee: false,
  },
  { id: 12,
    first_name: 'Jon',
    last_name: 'Williams',
    email: 'jonwilliams@workemail.com',
    password: 'password',
    phone: '1234567890',
    is_employee: true,
  },
  { id: 13,
    first_name: 'Kurt',
    last_name: 'Vardeman',
    email: 'kurtvardeman@email.com',
    password: 'password',
    phone: '1234567890',
    is_employee: false,
  },
  { id: 14,
    first_name: 'Kurt',
    last_name: 'Vardeman',
    email: 'kurtvardeman@workemail.com',
    password: 'password',
    phone: '1234567890',
    is_employee: true,
  },
];

module.exports = users;