const vehicles = [
  {
    id: 1,
    make_model: 'Chrystler',
    color: 'red',
    license_plate: 'SLK3920',
    user_id: 1,
  },
  {
    id: 2,
    make_model: 'Ford',
    color: 'black',
    license_plate: 'ABCD123',
    user_id: 1,
  },
  {
    id: 3,
    make_model: 'Toyota',
    color: 'blue',
    license_plate: 'DCBA321',
    user_id: 3,
  },
  {
    id: 4,
    make_model: 'Honda',
    color: 'silver',
    license_plate: 'XYZ987',
    user_id: 3,
  },
  {
    id: 5,
    make_model: 'Chevrolet',
    color: 'white',
    license_plate: 'QWERTY1',
    user_id: 5,
  },
  {
    id: 6,
    make_model: 'Nissan',
    color: 'green',
    license_plate: 'ASDFG2',
    user_id: 5,
  },
  {
    id: 7,
    make_model: 'Hyundai',
    color: 'gray',
    license_plate: 'ZXCVB3',
    user_id: 7,
  },
  {
    id: 8,
    make_model: 'Kia',
    color: 'purple',
    license_plate: 'POIUY4',
    user_id: 7,
  },
  {
    id: 9,
    make_model: 'Mazda',
    color: 'yellow',
    license_plate: 'LKJHG5',
    user_id: 9,
  },
  {
    id: 10,
    make_model: 'Subaru',
    color: 'orange',
    license_plate: 'MNBVC6',
    user_id: 9,
  },
  {
    id: 11,
    make_model: 'Volkswagen',
    color: 'brown',
    license_plate: 'REWQ12',
    user_id: 11,
  },
  {
    id: 12,
    make_model: 'Audi',
    color: 'silver',
    license_plate: 'UIOP34',
    user_id: 11,
  },
  {
    id: 13,
    make_model: 'BMW',
    color: 'black',
    license_plate: 'TREW56',
    user_id: 13,
  },
  {
    id: 14,
    make_model: 'Mercedes-Benz',
    color: 'red',
    license_plate: 'PLKM78',
    user_id: 13,
  },
  {
    id: 99,
    make_model: 'Honda',
    color: 'red',
    license_plate: '48lskd',
    user_id: 15,
  },
];

module.exports = vehicles;
